### ISSUE TITLE
Only keep 10 child spawns

### ISSUE THREAD

**Issue by zHaytam** [Mpdreamz/shellprogressbar#34]
Hello,

I have a task that spawns 165 tasks (sequentially) and I would like to keep the history of tasks finished, but when spawning more than what the window can handle, sometimes the new child shows, sometimes it doesn't (but the program is still working and ticking).

Is there a way to limit the number of children to like 10? And only collapse old ones when the limit was reached?

Thank you!

**Comment by zHaytam** [comment]
For now, I'm using the following workaround:
- Add every `ProgressBarOptions` created to a list.
- When the list has 10 elements and I need a new one, I set `CollapseWhenFinished` to true for the first element and I remove it.

This makes old children collapse since `DrawChildren` checks `Collapse`.

**Comment by Mpdreamz** [comment]
Hi @zHaytam 

Sorry for the late reply I **think** the new `WriteLine()` in `4.3.0` is a good way to print a summary of the completed task above the progressbar, this will also survive any collapsing.

Closing this because its an older issue (my bad). Let me know if this is something you still want, happy to learn more.
